version: '3.8'
services:
  chadracmulopo-website:
    container_name: chadracmulopo-website
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./config/Dockerfile
    image: antonioyosica/chadracmulopo:latest
    ports:
      - 3010:3000
    networks:
      - nginx-proxymanager_default
networks:
  nginx-proxymanager_default:
    external: true
